name: Deploy Rate to Lambda

on:
  push:
    paths:
      - "build/rate.js"

jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
        
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Node Env
        run: npm install && npm run build --if-present
      - name: Zip Send
        run: cp build/rate.js build/index.js && cd build && echo "${{ secrets.ENV_FILE }}" > .env && zip send.zip index.js .env
      - name: Deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: test
          zip_file: build/send.zip